version: "3.8"

services:
  ubuntu-latest:
    image: ubuntu:latest
    volumes:
      - ./scripts:/scripts
    entrypoint: /scripts/entrypoint.sh
    environment:
      - GIT_REPO=https://github.com/xXChampionsXx/youtube_player.git
      - GIT_BRANCH=main
      - GIT_DEST_PATH=/youtube-player
    ports:
      - "5173:5173"
      - "3001:3001"

volumes:
  app-volume:
